// Generated by sync-ui-snapshots.mjs — re-export shim around
// animate-ui's native component at @/components/animate-ui/components/buttons/button. Edit the
// underlying file (or pick `--ui custom`/`--ui shadcn`) to
// change behaviour; this file is overwritten on next sync.
export * from '@/components/animate-ui/components/buttons/button';
